// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MilkTeaMe.Repositories.Models;

public partial class PasswordResetToken
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Token { get; set; }

    public DateTime ExpiredAt { get; set; }
}